##
## EPITECH PROJECT, 2020
## arcade
## File description:
## graphicals makefile
##

all:
	make -C SDL
	make -C SFML
	make -C NCURSES

clean:
	make clean -C SDL
	make clean -C SFML
	make clean -C NCURSES

fclean:	clean
	make fclean -C SDL
	make fclean -C SFML
	make fclean -C NCURSES

re:	fclean all
