##
## EPITECH PROJECT, 2020
## arcade
## File description:
## graphicals makefile
##

all:
	make -C NCURSES
	make -C SFML
	make -C SDL

clean:
	make clean -C NCURSES
	make clean -C SFML
	make clean -C SDL

fclean:	clean
	make fclean -C NCURSES
	make fclean -C SFML
	make fclean -C SDL

re:	fclean all
