##
## EPITECH PROJECT, 2020
## arcade
## File description:
## graphicals makefile
##

all:
	make -C SDL
	make -C NCURSES
	make -C SFML

clean:
	make clean -C SDL
	make clean -C NCURSES
	make clean -C SFML

fclean:	clean
	make fclean -C SDL
	make fclean -C NCURSES
	make fclean -C SFML

re:	fclean all
