##
## EPITECH PROJECT, 2020
## arcade
## File description:
## games makefile
##

all:
	mkdir -p ../../games/
	make -C Nibbler
	
clean:
	make clean -C Nibbler

fclean:	clean
	make fclean -C Nibbler

re:	fclean all
